service: serverless-iidx-csv-parser

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  profile: mizukmb
  stage: production
package:
 exclude:
   - ./**
 include:
   - ./bin/**
   - ./iidx24_sinobuz_score.csv
functions:
  parse:
    handler: bin/main
    events:
      - http:
          path: iidx/parse
          method: get
  scrapbox:
    handler: bin/scrapbox
    events:
      - http:
          path: iidx/scrapbox
          method: get
